/**
 * W-2 스트레칭 데이터베이스
 *
 * @module lib/workout/stretching/database
 * @description 60개 스트레칭 운동 DB (ACSM, Janda, PNF 기반)
 * @see docs/specs/SDD-W-2-ADVANCED-STRETCHING.md
 *
 * 원리:
 * - 점탄성(Viscoelasticity): 정적 스트레칭 30초 이상 유지
 * - PNF: Contract-Relax 6초 수축 → 30초 이완
 * - ACSM: 주 2-3회, 15-60초, 2-4세트
 */

import type { StretchExercise } from '@/types/stretching';

// ============================================
// 상체 스트레칭 (20개)
// ============================================

/**
 * 흉근 스트레칭 (4개)
 */
const CHEST_STRETCHES: StretchExercise[] = [
  {
    id: 'str_chest_doorway',
    nameKo: '문틀 대흉근 스트레칭',
    nameEn: 'Doorway Pec Stretch',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['pectoralis_major', 'pectoralis_minor'],
    secondaryMuscles: ['deltoid'],
    equipment: ['wall'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '문틀이나 벽 코너에 서세요',
      '팔꿈치를 90도로 구부려 벽에 대세요',
      '한 발 앞으로 나가면서 가슴을 열어주세요',
      '스트레칭을 느끼며 30초간 유지하세요',
    ],
    breathingGuide: '코로 깊게 들이쉬고 입으로 천천히 내쉬세요',
    commonMistakes: ['어깨가 올라가는 것', '허리를 과도하게 젖히는 것'],
    contraindications: ['어깨 부상', '회전근개 파열'],
    modifications: [
      {
        condition: '어깨 통증',
        description: '팔꿈치 각도를 낮추세요 (60도)',
        adjustedDuration: 20,
      },
    ],
    redFlags: ['팔저림', '날카로운 통증'],
  },
  {
    id: 'str_chest_floor',
    nameKo: '바닥 대흉근 스트레칭',
    nameEn: 'Floor Pec Stretch',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['pectoralis_major'],
    secondaryMuscles: ['pectoralis_minor', 'serratus_anterior'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '매트에 엎드려 누우세요',
      '한 팔을 90도로 옆으로 뻗으세요',
      '반대쪽으로 몸을 굴려 스트레칭하세요',
      '30초 유지 후 반대쪽도 반복하세요',
    ],
    breathingGuide: '들숨에 이완, 날숨에 더 깊이 스트레칭',
    commonMistakes: ['목을 과도하게 돌리는 것'],
    contraindications: ['어깨 탈구 이력'],
    modifications: [],
    redFlags: ['팔 저림'],
  },
  {
    id: 'str_chest_wall_corner',
    nameKo: '벽 코너 대흉근 스트레칭',
    nameEn: 'Wall Corner Pec Stretch',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['pectoralis_major', 'pectoralis_minor'],
    secondaryMuscles: ['deltoid', 'serratus_anterior'],
    equipment: ['wall'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '벽 코너에 서서 양 팔을 벽에 대세요',
      '팔꿈치는 어깨 높이보다 약간 높게',
      '몸을 코너 쪽으로 기울이세요',
      '양쪽 가슴이 동시에 스트레칭되는 것을 느끼세요',
    ],
    breathingGuide: '깊은 호흡으로 가슴을 열어주세요',
    commonMistakes: ['허리가 과도하게 젖혀지는 것'],
    contraindications: ['어깨 충돌증후군'],
    modifications: [
      {
        condition: '어깨 불편',
        description: '팔꿈치를 낮추고 시행',
        adjustedDuration: 20,
      },
    ],
    redFlags: ['어깨 날카로운 통증'],
  },
  {
    id: 'str_chest_foam_roller',
    nameKo: '폼롤러 가슴 열기',
    nameEn: 'Foam Roller Chest Opener',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['pectoralis_major', 'pectoralis_minor'],
    secondaryMuscles: ['serratus_anterior'],
    equipment: ['foam_roller', 'mat'],
    difficulty: 'beginner',
    defaultDuration: 60,
    durationUnit: 'seconds',
    sets: 1,
    restBetweenSets: 0,
    instructions: [
      '폼롤러를 척추와 평행하게 놓으세요',
      '폼롤러 위에 등을 대고 누우세요',
      '양 팔을 옆으로 벌려 바닥에 내려놓으세요',
      '1분간 이완하며 가슴이 열리는 것을 느끼세요',
    ],
    breathingGuide: '복식호흡으로 깊게 이완하세요',
    commonMistakes: ['목이 뒤로 젖혀지는 것'],
    contraindications: ['척추 손상'],
    modifications: [
      {
        condition: '목 불편',
        description: '베개로 머리 받침',
      },
    ],
    redFlags: ['두통', '어지러움'],
  },
];

/**
 * 승모근/견갑거근 스트레칭 (4개)
 */
const TRAPEZIUS_STRETCHES: StretchExercise[] = [
  {
    id: 'str_upper_trap',
    nameKo: '상부 승모근 스트레칭',
    nameEn: 'Upper Trapezius Stretch',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['upper_trapezius'],
    secondaryMuscles: ['levator_scapulae'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 10,
    instructions: [
      '편하게 앉거나 서세요',
      '한 손으로 반대쪽 머리를 부드럽게 잡으세요',
      '귀를 어깨 쪽으로 기울이세요',
      '30초간 유지 후 반대쪽 반복',
    ],
    breathingGuide: '천천히 호흡하며 이완하세요',
    commonMistakes: ['어깨가 따라 올라가는 것', '너무 세게 당기는 것'],
    contraindications: ['경추 디스크'],
    modifications: [
      {
        condition: '목 통증',
        description: '손 사용 없이 머리 무게만으로',
        adjustedDuration: 20,
      },
    ],
    redFlags: ['두통', '팔 저림'],
  },
  {
    id: 'str_levator_scapulae',
    nameKo: '견갑거근 스트레칭',
    nameEn: 'Levator Scapulae Stretch',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['levator_scapulae'],
    secondaryMuscles: ['upper_trapezius'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 10,
    instructions: [
      '앉아서 한 손으로 의자 밑을 잡으세요',
      '반대 손으로 머리 뒤를 잡으세요',
      '턱을 당기며 대각선 아래로 고개를 숙이세요',
      '겨드랑이 방향으로 바라보세요',
    ],
    breathingGuide: '깊은 호흡으로 목 긴장을 풀어주세요',
    commonMistakes: ['숄더 쉬럭', '과도한 힘'],
    contraindications: ['경추 협착증'],
    modifications: [],
    redFlags: ['어지러움', '팔 저림'],
  },
  {
    id: 'str_neck_rotation',
    nameKo: '목 회전 스트레칭',
    nameEn: 'Neck Rotation Stretch',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['sternocleidomastoid', 'upper_trapezius'],
    secondaryMuscles: ['levator_scapulae'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 20,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 10,
    instructions: [
      '편하게 앉아 정면을 바라보세요',
      '천천히 고개를 왼쪽으로 돌리세요',
      '20초간 유지 후 정면으로 돌아오세요',
      '반대쪽도 같은 방법으로 반복하세요',
    ],
    breathingGuide: '돌리는 동안 자연스럽게 호흡하세요',
    commonMistakes: ['어깨가 따라 돌아가는 것'],
    contraindications: ['경추 불안정'],
    modifications: [],
    redFlags: ['어지러움', '시야 흐림'],
  },
  {
    id: 'str_neck_lateral_flexion',
    nameKo: '목 옆으로 기울이기',
    nameEn: 'Lateral Neck Flexion',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['upper_trapezius', 'levator_scapulae'],
    secondaryMuscles: ['sternocleidomastoid'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 20,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 10,
    instructions: [
      '편하게 앉아 정면을 바라보세요',
      '머리를 옆으로 기울여 귀가 어깨에 가까워지게 하세요',
      '반대쪽 어깨는 내린 채로 유지하세요',
      '20초 유지 후 반대쪽 반복',
    ],
    breathingGuide: '깊게 호흡하며 이완하세요',
    commonMistakes: ['어깨가 올라가는 것'],
    contraindications: ['경추 디스크'],
    modifications: [],
    redFlags: ['팔 저림'],
  },
];

/**
 * 후두하근/경추 스트레칭 (4개)
 */
const CERVICAL_STRETCHES: StretchExercise[] = [
  {
    id: 'str_suboccipitals',
    nameKo: '후두하근 스트레칭 (친 턱)',
    nameEn: 'Chin Tuck',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['suboccipitals'],
    secondaryMuscles: ['sternocleidomastoid'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 10,
    durationUnit: 'seconds',
    sets: 10,
    restBetweenSets: 5,
    instructions: [
      '편하게 앉아 정면을 바라보세요',
      '턱을 뒤로 당기듯이 이중턱을 만드세요',
      '시선은 정면을 유지하세요',
      '10초 유지 후 이완, 10회 반복',
    ],
    breathingGuide: '유지 시 정상 호흡',
    commonMistakes: ['고개를 숙이는 것', '목을 과도하게 젖히는 것'],
    contraindications: [],
    modifications: [
      {
        condition: '거북목 심함',
        description: '벽에 등 대고 연습',
      },
    ],
    redFlags: ['두통'],
  },
  {
    id: 'str_chin_tuck_supine',
    nameKo: '누워서 친 턱',
    nameEn: 'Supine Chin Tuck',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['suboccipitals', 'deep_neck_flexors'],
    secondaryMuscles: ['sternocleidomastoid'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 10,
    durationUnit: 'seconds',
    sets: 10,
    restBetweenSets: 5,
    instructions: [
      '등을 대고 편하게 누우세요',
      '턱을 살짝 당겨 목 뒤가 바닥에 닿게 하세요',
      '목 뒤에 손을 넣어 공간이 줄어드는지 확인하세요',
      '10초 유지 후 이완, 10회 반복',
    ],
    breathingGuide: '정상 호흡 유지',
    commonMistakes: ['머리를 들어올리는 것'],
    contraindications: [],
    modifications: [],
    redFlags: ['목 통증 악화'],
  },
  {
    id: 'str_deep_neck_flexor',
    nameKo: '심부 경추 굴곡근 강화',
    nameEn: 'Deep Neck Flexor Activation',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['deep_neck_flexors'],
    secondaryMuscles: ['sternocleidomastoid'],
    equipment: ['mat'],
    difficulty: 'intermediate',
    defaultDuration: 10,
    durationUnit: 'seconds',
    sets: 10,
    restBetweenSets: 5,
    instructions: [
      '등을 대고 무릎을 세워 누우세요',
      '턱을 살짝 당긴 상태에서 머리를 1cm 들어올리세요',
      '이마가 아닌 목 앞쪽 근육이 작용하는지 확인하세요',
      '10초 유지 후 천천히 내려놓으세요',
    ],
    breathingGuide: '유지 중 정상 호흡',
    commonMistakes: ['흉쇄유돌근으로 들어올리는 것'],
    contraindications: ['경추 불안정'],
    modifications: [
      {
        condition: '목 약함',
        description: '들어올리지 않고 누른 채로 유지',
        adjustedDuration: 5,
      },
    ],
    redFlags: ['목 통증'],
  },
  {
    id: 'str_scm_stretch',
    nameKo: '흉쇄유돌근 스트레칭',
    nameEn: 'SCM Stretch',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['sternocleidomastoid'],
    secondaryMuscles: ['upper_trapezius'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 20,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 10,
    instructions: [
      '편하게 앉아 한 손을 쇄골에 올리세요',
      '고개를 반대쪽으로 돌리고 살짝 뒤로 젖히세요',
      '목 앞쪽 스트레칭을 느끼세요',
      '20초 유지 후 반대쪽 반복',
    ],
    breathingGuide: '깊은 호흡으로 이완',
    commonMistakes: ['너무 세게 젖히는 것'],
    contraindications: ['경추 동맥 문제'],
    modifications: [],
    redFlags: ['어지러움', '두통'],
  },
];

/**
 * 어깨/견갑대 스트레칭 (4개)
 */
const SHOULDER_STRETCHES: StretchExercise[] = [
  {
    id: 'str_cross_body_shoulder',
    nameKo: '크로스 바디 어깨 스트레칭',
    nameEn: 'Cross-Body Shoulder Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['deltoid', 'rhomboids'],
    secondaryMuscles: ['upper_trapezius'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '한 팔을 가슴 앞으로 쭉 뻗으세요',
      '반대 손으로 팔꿈치 위를 잡아당기세요',
      '어깨 뒤쪽 스트레칭을 느끼세요',
      '30초 유지 후 반대쪽 반복',
    ],
    breathingGuide: '천천히 깊게 호흡하세요',
    commonMistakes: ['어깨가 올라가는 것'],
    contraindications: ['어깨 충돌증후군'],
    modifications: [],
    redFlags: ['어깨 날카로운 통증'],
  },
  {
    id: 'str_behind_back_shoulder',
    nameKo: '등 뒤 어깨 스트레칭',
    nameEn: 'Behind Back Shoulder Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['deltoid', 'pectoralis_major'],
    secondaryMuscles: ['rotator_cuff'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '양 손을 등 뒤에서 깍지 끼세요',
      '팔을 천천히 위로 들어올리세요',
      '가슴을 열고 어깨를 뒤로 당기세요',
      '30초간 유지하세요',
    ],
    breathingGuide: '가슴을 열며 깊게 호흡하세요',
    commonMistakes: ['상체를 앞으로 숙이는 것'],
    contraindications: ['어깨 회전근개 부상'],
    modifications: [
      {
        condition: '손이 닿지 않음',
        description: '수건을 사용하세요',
      },
    ],
    redFlags: ['어깨 통증'],
  },
  {
    id: 'str_thread_needle',
    nameKo: '바늘 끼우기',
    nameEn: 'Thread the Needle',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['rhomboids', 'mid_lower_trapezius'],
    secondaryMuscles: ['latissimus_dorsi'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '네발기기 자세로 시작하세요',
      '한 팔을 반대 팔 아래로 밀어넣으세요',
      '어깨와 머리를 바닥에 내려놓으세요',
      '30초 유지 후 반대쪽 반복',
    ],
    breathingGuide: '깊게 호흡하며 등을 이완하세요',
    commonMistakes: ['골반이 틀어지는 것'],
    contraindications: ['어깨 부상'],
    modifications: [],
    redFlags: ['어깨 날카로운 통증'],
  },
  {
    id: 'str_lat_stretch_wall',
    nameKo: '벽 광배근 스트레칭',
    nameEn: 'Wall Lat Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['latissimus_dorsi'],
    secondaryMuscles: ['serratus_anterior', 'obliques'],
    equipment: ['wall'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '벽 앞에 서서 양 손을 벽에 대세요',
      '엉덩이를 뒤로 빼며 상체를 숙이세요',
      '팔을 벽에 댄 채로 유지하세요',
      '옆구리와 겨드랑이 스트레칭을 느끼세요',
    ],
    breathingGuide: '날숨에 더 깊이 스트레칭',
    commonMistakes: ['허리가 과도하게 아치되는 것'],
    contraindications: ['어깨 부상'],
    modifications: [],
    redFlags: ['어깨 통증'],
  },
];

/**
 * 척추/코어 스트레칭 (4개)
 */
const SPINE_STRETCHES: StretchExercise[] = [
  {
    id: 'str_cat_cow',
    nameKo: '고양이-소 스트레칭',
    nameEn: 'Cat-Cow Stretch',
    type: 'dynamic',
    category: 'general_flexibility',
    targetMuscles: ['erector_spinae', 'rectus_abdominis'],
    secondaryMuscles: ['multifidus'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 10,
    durationUnit: 'reps',
    sets: 2,
    restBetweenSets: 10,
    instructions: [
      '네발기기 자세로 시작하세요',
      '들숨에 배를 내리고 고개를 들어 소 자세',
      '날숨에 등을 둥글게 말고 고개를 숙여 고양이 자세',
      '10회 부드럽게 반복하세요',
    ],
    breathingGuide: '움직임과 호흡을 동기화하세요',
    commonMistakes: ['동작이 너무 빠른 것'],
    contraindications: ['급성 요통'],
    modifications: [],
    redFlags: ['허리 날카로운 통증'],
  },
  {
    id: 'str_childs_pose',
    nameKo: '아이 자세',
    nameEn: "Child's Pose",
    type: 'static',
    category: 'recovery',
    targetMuscles: ['erector_spinae', 'quadratus_lumborum'],
    secondaryMuscles: ['latissimus_dorsi', 'gluteus_maximus'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 60,
    durationUnit: 'seconds',
    sets: 1,
    restBetweenSets: 0,
    instructions: [
      '무릎을 꿇고 앉으세요',
      '이마를 바닥에 대고 팔을 앞으로 뻗으세요',
      '엉덩이를 뒤꿈치 쪽으로 내리세요',
      '깊게 호흡하며 1분간 이완하세요',
    ],
    breathingGuide: '복식호흡으로 등을 넓히세요',
    commonMistakes: ['엉덩이가 뜨는 것'],
    contraindications: ['무릎 부상'],
    modifications: [
      {
        condition: '무릎 불편',
        description: '무릎 아래 담요',
      },
    ],
    redFlags: ['무릎 통증'],
  },
  {
    id: 'str_seated_spinal_twist',
    nameKo: '앉아서 척추 비틀기',
    nameEn: 'Seated Spinal Twist',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['obliques', 'erector_spinae'],
    secondaryMuscles: ['quadratus_lumborum'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '다리를 뻗고 앉으세요',
      '한 무릎을 세워 반대쪽 다리 바깥에 두세요',
      '상체를 세운 무릎 방향으로 돌리세요',
      '30초 유지 후 반대쪽 반복',
    ],
    breathingGuide: '날숨에 조금 더 비트세요',
    commonMistakes: ['등이 둥글게 되는 것'],
    contraindications: ['디스크 탈출'],
    modifications: [],
    redFlags: ['허리 방사통'],
  },
  {
    id: 'str_prone_press_up',
    nameKo: '엎드려 상체 들기',
    nameEn: 'Prone Press Up',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['rectus_abdominis'],
    secondaryMuscles: ['iliopsoas'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 10,
    durationUnit: 'seconds',
    sets: 5,
    restBetweenSets: 10,
    instructions: [
      '엎드려 누워 손을 어깨 옆에 두세요',
      '하체는 바닥에 붙인 채 상체만 들어올리세요',
      '팔꿈치를 펴고 허리를 뒤로 젖히세요',
      '10초 유지 후 천천히 내려오세요',
    ],
    breathingGuide: '들어올리며 들숨, 내리며 날숨',
    commonMistakes: ['골반이 따라 올라가는 것'],
    contraindications: ['척추관 협착증', '급성 요통'],
    modifications: [
      {
        condition: '허리 불편',
        description: '팔꿈치만 펴세요',
        adjustedDuration: 5,
      },
    ],
    redFlags: ['다리 저림'],
  },
];

// ============================================
// 하체 스트레칭 (20개)
// ============================================

/**
 * 장요근/대퇴직근 스트레칭 (4개)
 */
const HIP_FLEXOR_STRETCHES: StretchExercise[] = [
  {
    id: 'str_hip_flexor_kneeling',
    nameKo: '무릎 꿇고 장요근 스트레칭',
    nameEn: 'Kneeling Hip Flexor Stretch',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['iliopsoas', 'rectus_femoris'],
    secondaryMuscles: ['tensor_fasciae_latae'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '한 무릎을 바닥에 대고 다른 발은 앞에 세우세요',
      '골반을 후방 경사로 틸트하세요 (복근 조이기)',
      '몸을 앞으로 이동하며 고관절 앞쪽 스트레칭',
      '30초 유지 후 다리 바꿔서 반복',
    ],
    breathingGuide: '날숨에 골반 틸트를 유지하세요',
    commonMistakes: ['허리를 과도하게 젖히는 것', '골반이 틀어지는 것'],
    contraindications: ['무릎 부상'],
    modifications: [
      {
        condition: '무릎 통증',
        description: '무릎 아래 쿠션 사용',
      },
    ],
    redFlags: ['무릎 통증 악화'],
  },
  {
    id: 'str_hip_flexor_standing',
    nameKo: '서서 장요근 스트레칭',
    nameEn: 'Standing Hip Flexor Stretch',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['iliopsoas'],
    secondaryMuscles: ['rectus_femoris'],
    equipment: ['wall'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '벽이나 의자를 잡고 한 발을 뒤로 뻗으세요',
      '뒷발 뒤꿈치를 땅에 붙이고 골반을 앞으로 밀어주세요',
      '배에 힘을 주어 허리가 젖혀지지 않게 하세요',
      '30초 유지 후 다리 바꿔서 반복',
    ],
    breathingGuide: '깊은 호흡 유지',
    commonMistakes: ['허리 과신전'],
    contraindications: [],
    modifications: [],
    redFlags: [],
  },
  {
    id: 'str_couch_stretch',
    nameKo: '소파 스트레칭',
    nameEn: 'Couch Stretch',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['iliopsoas', 'rectus_femoris'],
    secondaryMuscles: ['quadriceps'],
    equipment: ['wall'],
    difficulty: 'intermediate',
    defaultDuration: 60,
    durationUnit: 'seconds',
    sets: 1,
    restBetweenSets: 0,
    instructions: [
      '벽을 등지고 무릎을 꿇으세요',
      '한 발은 앞에 세우고, 뒷무릎과 발등을 벽에 대세요',
      '상체를 세우고 골반을 앞으로 밀어주세요',
      '60초 유지 후 다리 교체',
    ],
    breathingGuide: '깊은 호흡으로 이완하세요',
    commonMistakes: ['허리가 과도하게 젖혀지는 것'],
    contraindications: ['무릎 부상', '슬개골 문제'],
    modifications: [
      {
        condition: '무릎 불편',
        description: '베개를 무릎 아래에',
      },
    ],
    redFlags: ['무릎 날카로운 통증'],
  },
  {
    id: 'str_thomas_test_stretch',
    nameKo: '토마스 테스트 스트레칭',
    nameEn: 'Thomas Test Stretch',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['iliopsoas', 'rectus_femoris'],
    secondaryMuscles: ['tensor_fasciae_latae'],
    equipment: ['mat'],
    difficulty: 'intermediate',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '침대나 벤치 끝에 누워 한 다리를 가슴으로 당기세요',
      '다른 다리는 자연스럽게 아래로 내려가게 하세요',
      '허벅지 앞쪽 스트레칭을 느끼세요',
      '30초 유지 후 다리 교체',
    ],
    breathingGuide: '깊은 호흡으로 이완',
    commonMistakes: ['허리가 아치되는 것'],
    contraindications: ['고관절 문제'],
    modifications: [],
    redFlags: ['고관절 통증'],
  },
];

/**
 * 햄스트링 스트레칭 (4개)
 */
const HAMSTRING_STRETCHES: StretchExercise[] = [
  {
    id: 'str_hamstring_standing',
    nameKo: '서서 햄스트링 스트레칭',
    nameEn: 'Standing Hamstring Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['hamstrings'],
    secondaryMuscles: ['gastrocnemius'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '한 발을 앞으로 내밀고 뒤꿈치만 땅에 대세요',
      '뒷다리 무릎을 살짝 구부리세요',
      '엉덩이를 뒤로 빼며 상체를 앞으로 숙이세요',
      '허벅지 뒤쪽 스트레칭을 느끼세요',
    ],
    breathingGuide: '날숨에 더 깊이 숙이세요',
    commonMistakes: ['등을 구부리는 것', '무릎을 완전히 펴는 것'],
    contraindications: ['좌골신경통'],
    modifications: [
      {
        condition: '유연성 부족',
        description: '높은 곳에 발 올리기',
      },
    ],
    redFlags: ['다리 저림'],
  },
  {
    id: 'str_hamstring_supine',
    nameKo: '누워서 햄스트링 스트레칭',
    nameEn: 'Supine Hamstring Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['hamstrings'],
    secondaryMuscles: ['gastrocnemius'],
    equipment: ['mat', 'resistance_band'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '등을 대고 누우세요',
      '한 다리를 천장으로 들어올리세요',
      '밴드나 수건으로 발을 잡고 당기세요',
      '무릎은 살짝 구부려도 됩니다',
    ],
    breathingGuide: '깊은 호흡으로 이완하세요',
    commonMistakes: ['골반이 뜨는 것', '목에 긴장'],
    contraindications: [],
    modifications: [],
    redFlags: ['좌골신경 방사통'],
  },
  {
    id: 'str_seated_hamstring',
    nameKo: '앉아서 햄스트링 스트레칭',
    nameEn: 'Seated Hamstring Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['hamstrings'],
    secondaryMuscles: ['erector_spinae'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '다리를 앞으로 뻗고 앉으세요',
      '허리를 곧게 펴고 상체를 앞으로 숙이세요',
      '손으로 발이나 정강이를 잡으세요',
      '햄스트링 스트레칭을 느끼며 30초 유지',
    ],
    breathingGuide: '날숨에 조금씩 더 숙이세요',
    commonMistakes: ['등을 둥글게 마는 것'],
    contraindications: ['디스크 탈출'],
    modifications: [
      {
        condition: '유연성 부족',
        description: '무릎을 살짝 구부리세요',
      },
    ],
    redFlags: ['허리 방사통'],
  },
  {
    id: 'str_doorway_hamstring',
    nameKo: '문틀 햄스트링 스트레칭',
    nameEn: 'Doorway Hamstring Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['hamstrings'],
    secondaryMuscles: ['gastrocnemius'],
    equipment: ['wall'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '문틀 옆에 등을 대고 누우세요',
      '한 다리를 문틀 벽에 올리세요',
      '엉덩이를 문틀에 가까이 붙이세요',
      '반대 다리는 바닥에 두고 30초 유지',
    ],
    breathingGuide: '깊게 호흡하며 이완',
    commonMistakes: ['엉덩이가 벽에서 멀어지는 것'],
    contraindications: [],
    modifications: [],
    redFlags: ['좌골신경통 악화'],
  },
];

/**
 * 둔근/이상근 스트레칭 (4개)
 */
const GLUTE_STRETCHES: StretchExercise[] = [
  {
    id: 'str_piriformis_seated',
    nameKo: '앉아서 이상근 스트레칭',
    nameEn: 'Seated Piriformis Stretch',
    type: 'static',
    category: 'posture_correction',
    targetMuscles: ['piriformis'],
    secondaryMuscles: ['gluteus_maximus', 'gluteus_medius'],
    equipment: ['chair'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '의자에 앉아 한 발목을 반대쪽 무릎 위에 올리세요',
      '상체를 곧게 펴고 앞으로 기울이세요',
      '엉덩이 깊은 곳에서 스트레칭을 느끼세요',
      '30초 후 다리를 바꾸세요',
    ],
    breathingGuide: '깊은 호흡 유지',
    commonMistakes: ['등이 구부러지는 것'],
    contraindications: ['좌골신경통 급성기'],
    modifications: [
      {
        condition: '무릎 통증',
        description: '발목을 낮은 위치에 올리세요',
      },
    ],
    redFlags: ['다리 저림 악화'],
  },
  {
    id: 'str_pigeon_pose',
    nameKo: '비둘기 자세',
    nameEn: 'Pigeon Pose',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['piriformis', 'gluteus_maximus'],
    secondaryMuscles: ['iliopsoas'],
    equipment: ['mat'],
    difficulty: 'intermediate',
    defaultDuration: 60,
    durationUnit: 'seconds',
    sets: 1,
    restBetweenSets: 0,
    instructions: [
      '네발기기 자세에서 시작하세요',
      '한 무릎을 앞으로 가져와 바닥에 내려놓으세요',
      '뒷다리를 뒤로 뻗으세요',
      '상체를 앞으로 숙여 깊은 스트레칭을 느끼세요',
    ],
    breathingGuide: '깊은 호흡으로 긴장을 풀어주세요',
    commonMistakes: ['골반이 틀어지는 것'],
    contraindications: ['무릎 부상', '고관절 부상'],
    modifications: [
      {
        condition: '유연성 부족',
        description: '베개를 엉덩이 아래에 받치세요',
      },
    ],
    redFlags: ['무릎 통증'],
  },
  {
    id: 'str_figure_four_supine',
    nameKo: '누워서 4자 스트레칭',
    nameEn: 'Supine Figure Four',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['piriformis', 'gluteus_maximus'],
    secondaryMuscles: ['gluteus_medius'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '등을 대고 무릎을 세워 누우세요',
      '한 발목을 반대쪽 무릎 위에 올리세요',
      '아래 다리를 두 손으로 잡아 가슴 쪽으로 당기세요',
      '엉덩이 스트레칭을 느끼며 30초 유지',
    ],
    breathingGuide: '깊게 호흡하며 이완',
    commonMistakes: ['목이 긴장되는 것'],
    contraindications: [],
    modifications: [
      {
        condition: '손이 닿지 않음',
        description: '수건으로 다리 잡기',
      },
    ],
    redFlags: ['허리 통증'],
  },
  {
    id: 'str_glute_stretch_wall',
    nameKo: '벽 둔근 스트레칭',
    nameEn: 'Wall Glute Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['gluteus_maximus', 'gluteus_medius'],
    secondaryMuscles: ['piriformis'],
    equipment: ['wall'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '벽에 등을 대고 서세요',
      '한 발목을 반대쪽 무릎 위에 올리세요',
      '천천히 무릎을 구부려 앉는 자세로',
      '30초 유지 후 다리 교체',
    ],
    breathingGuide: '천천히 깊게 호흡',
    commonMistakes: ['등이 벽에서 떨어지는 것'],
    contraindications: ['무릎 부상'],
    modifications: [],
    redFlags: ['무릎 통증'],
  },
];

/**
 * 대퇴사두근 스트레칭 (2개)
 */
const QUADRICEPS_STRETCHES: StretchExercise[] = [
  {
    id: 'str_standing_quad',
    nameKo: '서서 대퇴사두근 스트레칭',
    nameEn: 'Standing Quad Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['quadriceps', 'rectus_femoris'],
    secondaryMuscles: ['iliopsoas'],
    equipment: ['wall'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '벽이나 의자를 잡고 한 발로 서세요',
      '반대쪽 발목을 손으로 잡아 엉덩이 쪽으로 당기세요',
      '무릎을 함께 붙이세요',
      '허벅지 앞쪽 스트레칭을 느끼며 30초 유지',
    ],
    breathingGuide: '천천히 깊게 호흡',
    commonMistakes: ['허리가 과도하게 젖혀지는 것'],
    contraindications: ['무릎 부상'],
    modifications: [
      {
        condition: '균형 어려움',
        description: '벽에 기대어 하세요',
      },
    ],
    redFlags: ['무릎 통증'],
  },
  {
    id: 'str_prone_quad',
    nameKo: '엎드려 대퇴사두근 스트레칭',
    nameEn: 'Prone Quad Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['quadriceps', 'rectus_femoris'],
    secondaryMuscles: ['iliopsoas'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '엎드려 누우세요',
      '한 손으로 같은 쪽 발목을 잡으세요',
      '발을 엉덩이 쪽으로 당기세요',
      '30초 유지 후 반대쪽 반복',
    ],
    breathingGuide: '깊게 호흡하며 이완',
    commonMistakes: ['허리가 아치되는 것'],
    contraindications: ['무릎 부상'],
    modifications: [
      {
        condition: '손이 닿지 않음',
        description: '수건이나 밴드 사용',
      },
    ],
    redFlags: ['무릎 날카로운 통증'],
  },
];

/**
 * 내전근/IT밴드 스트레칭 (3개)
 */
const ADDUCTOR_STRETCHES: StretchExercise[] = [
  {
    id: 'str_butterfly',
    nameKo: '나비 자세',
    nameEn: 'Butterfly Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['adductors'],
    secondaryMuscles: ['iliopsoas'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '앉아서 발바닥을 맞대세요',
      '발을 몸 쪽으로 당기세요',
      '무릎을 부드럽게 바닥 쪽으로 누르세요',
      '허리를 곧게 펴고 30초 유지',
    ],
    breathingGuide: '날숨에 무릎을 더 내리세요',
    commonMistakes: ['등이 둥글게 되는 것'],
    contraindications: ['무릎 부상', '고관절 문제'],
    modifications: [],
    redFlags: ['무릎 통증'],
  },
  {
    id: 'str_side_lunge_adductor',
    nameKo: '사이드 런지 내전근 스트레칭',
    nameEn: 'Side Lunge Adductor Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['adductors'],
    secondaryMuscles: ['hamstrings', 'gluteus_medius'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '다리를 넓게 벌리고 서세요',
      '한쪽 무릎을 구부리고 반대쪽 다리는 펴세요',
      '무게 중심을 구부린 다리 쪽으로 옮기세요',
      '펴진 다리 안쪽 스트레칭 느끼며 30초 유지',
    ],
    breathingGuide: '깊게 호흡하며 이완',
    commonMistakes: ['무릎이 발끝을 넘어가는 것'],
    contraindications: ['무릎 부상'],
    modifications: [],
    redFlags: ['무릎 통증'],
  },
  {
    id: 'str_it_band_standing',
    nameKo: '서서 IT밴드 스트레칭',
    nameEn: 'Standing IT Band Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['iliotibial_band', 'tensor_fasciae_latae'],
    secondaryMuscles: ['gluteus_medius'],
    equipment: ['wall'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '벽 옆에 서서 한 손으로 벽을 잡으세요',
      '바깥쪽 다리를 안쪽 다리 뒤로 교차하세요',
      '골반을 벽 쪽으로 밀어주세요',
      '바깥쪽 허벅지 스트레칭 느끼며 30초 유지',
    ],
    breathingGuide: '깊게 호흡하며 측면 스트레칭',
    commonMistakes: ['상체가 기우는 것'],
    contraindications: [],
    modifications: [],
    redFlags: ['무릎 통증'],
  },
];

/**
 * 종아리 스트레칭 (3개)
 */
const CALF_STRETCHES: StretchExercise[] = [
  {
    id: 'str_calf_wall',
    nameKo: '벽 종아리 스트레칭',
    nameEn: 'Wall Calf Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['gastrocnemius'],
    secondaryMuscles: ['soleus'],
    equipment: ['wall'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '벽을 마주 보고 손을 벽에 대세요',
      '한 발을 뒤로 뻗고 뒤꿈치를 바닥에 붙이세요',
      '앞 무릎을 구부리며 몸을 벽 쪽으로 기울이세요',
      '종아리 스트레칭 느끼며 30초 유지',
    ],
    breathingGuide: '천천히 깊게 호흡',
    commonMistakes: ['뒤꿈치가 뜨는 것'],
    contraindications: ['아킬레스건 부상'],
    modifications: [],
    redFlags: ['아킬레스건 통증'],
  },
  {
    id: 'str_soleus_wall',
    nameKo: '벽 가자미근 스트레칭',
    nameEn: 'Wall Soleus Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['soleus'],
    secondaryMuscles: ['gastrocnemius'],
    equipment: ['wall'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '벽을 마주 보고 손을 벽에 대세요',
      '한 발을 뒤로 뻗고 무릎을 살짝 구부리세요',
      '뒤꿈치는 바닥에 붙인 채로 유지',
      '종아리 아래쪽 스트레칭 느끼며 30초 유지',
    ],
    breathingGuide: '천천히 호흡',
    commonMistakes: ['무릎을 완전히 펴는 것'],
    contraindications: ['아킬레스건 부상'],
    modifications: [],
    redFlags: ['아킬레스건 통증'],
  },
  {
    id: 'str_step_calf',
    nameKo: '계단 종아리 스트레칭',
    nameEn: 'Step Calf Stretch',
    type: 'static',
    category: 'general_flexibility',
    targetMuscles: ['gastrocnemius', 'soleus'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '계단 끝에 앞발만 올리세요',
      '뒤꿈치를 천천히 아래로 내리세요',
      '종아리가 충분히 늘어나는 것을 느끼세요',
      '30초 유지',
    ],
    breathingGuide: '깊게 호흡',
    commonMistakes: ['균형을 잃는 것'],
    contraindications: ['아킬레스건 부상'],
    modifications: [
      {
        condition: '균형 어려움',
        description: '난간을 잡으세요',
      },
    ],
    redFlags: ['날카로운 통증'],
  },
];

// ============================================
// 동적 스트레칭 (워밍업) - 10개
// ============================================

const DYNAMIC_STRETCHES: StretchExercise[] = [
  {
    id: 'dyn_leg_swings',
    nameKo: '다리 스윙',
    nameEn: 'Leg Swings',
    type: 'dynamic',
    category: 'sport_warmup',
    targetMuscles: ['hamstrings', 'iliopsoas', 'adductors'],
    secondaryMuscles: ['quadriceps'],
    equipment: ['wall'],
    difficulty: 'beginner',
    defaultDuration: 10,
    durationUnit: 'reps',
    sets: 2,
    restBetweenSets: 10,
    instructions: [
      '벽을 잡고 옆으로 서세요',
      '안쪽 다리를 앞뒤로 스윙하세요',
      '점점 스윙 범위를 늘려가세요',
      '10회 후 좌우 스윙으로 바꾸세요',
    ],
    breathingGuide: '자연스러운 호흡',
    commonMistakes: ['상체가 흔들리는 것'],
    contraindications: ['고관절 부상'],
    modifications: [],
    redFlags: ['관절 통증'],
  },
  {
    id: 'dyn_arm_circles',
    nameKo: '팔 돌리기',
    nameEn: 'Arm Circles',
    type: 'dynamic',
    category: 'sport_warmup',
    targetMuscles: ['deltoid', 'rotator_cuff'],
    secondaryMuscles: ['pectoralis_major', 'upper_trapezius'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 10,
    durationUnit: 'reps',
    sets: 2,
    restBetweenSets: 10,
    instructions: [
      '양팔을 옆으로 뻗으세요',
      '작은 원을 그리며 앞으로 돌리세요',
      '점점 원을 크게 만드세요',
      '10회 후 반대 방향으로 반복',
    ],
    breathingGuide: '자연스러운 호흡',
    commonMistakes: ['어깨가 올라가는 것'],
    contraindications: ['어깨 충돌증후군'],
    modifications: [],
    redFlags: [],
  },
  {
    id: 'dyn_hip_circles',
    nameKo: '골반 돌리기',
    nameEn: 'Hip Circles',
    type: 'dynamic',
    category: 'sport_warmup',
    targetMuscles: ['iliopsoas', 'gluteus_medius'],
    secondaryMuscles: ['adductors', 'quadratus_lumborum'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 10,
    durationUnit: 'reps',
    sets: 2,
    restBetweenSets: 10,
    instructions: [
      '서서 손을 허리에 올리세요',
      '골반으로 큰 원을 그리세요',
      '시계방향으로 10회',
      '반시계방향으로 10회 반복',
    ],
    breathingGuide: '자연스러운 호흡',
    commonMistakes: ['무릎이 움직이는 것'],
    contraindications: [],
    modifications: [],
    redFlags: [],
  },
  {
    id: 'dyn_walking_lunge',
    nameKo: '워킹 런지',
    nameEn: 'Walking Lunge',
    type: 'dynamic',
    category: 'sport_warmup',
    targetMuscles: ['quadriceps', 'gluteus_maximus', 'iliopsoas'],
    secondaryMuscles: ['hamstrings', 'adductors'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 10,
    durationUnit: 'reps',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '서서 한 발을 앞으로 크게 내딛으세요',
      '뒷무릎이 바닥에 거의 닿을 때까지 낮추세요',
      '앞발로 밀어 일어나며 다음 발을 내딛으세요',
      '교대로 10회 반복',
    ],
    breathingGuide: '내려갈 때 들숨, 올라올 때 날숨',
    commonMistakes: ['무릎이 발끝을 넘어가는 것'],
    contraindications: ['무릎 부상'],
    modifications: [
      {
        condition: '무릎 불편',
        description: '깊이를 줄이세요',
      },
    ],
    redFlags: ['무릎 통증'],
  },
  {
    id: 'dyn_torso_twist',
    nameKo: '상체 회전',
    nameEn: 'Torso Twist',
    type: 'dynamic',
    category: 'sport_warmup',
    targetMuscles: ['obliques', 'erector_spinae'],
    secondaryMuscles: ['latissimus_dorsi'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 10,
    durationUnit: 'reps',
    sets: 2,
    restBetweenSets: 10,
    instructions: [
      '양발을 어깨너비로 벌리고 서세요',
      '팔을 가슴 앞에서 교차하세요',
      '상체를 좌우로 부드럽게 회전하세요',
      '골반은 정면을 유지하세요',
    ],
    breathingGuide: '회전하며 날숨',
    commonMistakes: ['골반이 따라 움직이는 것'],
    contraindications: ['허리 디스크'],
    modifications: [],
    redFlags: ['허리 통증'],
  },
  {
    id: 'dyn_high_knees',
    nameKo: '높이 뛰기',
    nameEn: 'High Knees',
    type: 'dynamic',
    category: 'sport_warmup',
    targetMuscles: ['iliopsoas', 'quadriceps'],
    secondaryMuscles: ['rectus_abdominis'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 20,
    durationUnit: 'reps',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '제자리에서 달리기 자세로 시작하세요',
      '무릎을 허리 높이까지 들어올리세요',
      '팔을 자연스럽게 교대로 스윙하세요',
      '20회 반복',
    ],
    breathingGuide: '리듬에 맞춰 호흡',
    commonMistakes: ['상체가 뒤로 젖혀지는 것'],
    contraindications: ['무릎 부상', '심장 질환'],
    modifications: [
      {
        condition: '체력 약함',
        description: '속도를 줄이세요',
      },
    ],
    redFlags: ['어지러움', '가슴 통증'],
  },
  {
    id: 'dyn_butt_kicks',
    nameKo: '버트 킥',
    nameEn: 'Butt Kicks',
    type: 'dynamic',
    category: 'sport_warmup',
    targetMuscles: ['hamstrings', 'quadriceps'],
    secondaryMuscles: ['gluteus_maximus'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 20,
    durationUnit: 'reps',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '제자리에서 달리기 자세로 시작하세요',
      '뒤꿈치가 엉덩이에 닿도록 다리를 접으세요',
      '팔을 자연스럽게 스윙하세요',
      '20회 반복',
    ],
    breathingGuide: '리듬에 맞춰 호흡',
    commonMistakes: ['상체가 앞으로 숙여지는 것'],
    contraindications: ['무릎 부상'],
    modifications: [],
    redFlags: ['무릎 통증'],
  },
  {
    id: 'dyn_inchworm',
    nameKo: '인치웜',
    nameEn: 'Inchworm',
    type: 'dynamic',
    category: 'sport_warmup',
    targetMuscles: ['hamstrings', 'rectus_abdominis'],
    secondaryMuscles: ['deltoid', 'pectoralis_major'],
    equipment: ['mat'],
    difficulty: 'intermediate',
    defaultDuration: 6,
    durationUnit: 'reps',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '서서 상체를 숙여 손을 바닥에 대세요',
      '손을 앞으로 걸어 플랭크 자세로',
      '다시 손을 뒤로 걸어 서있는 자세로',
      '6회 반복',
    ],
    breathingGuide: '움직임에 맞춰 자연스럽게 호흡',
    commonMistakes: ['무릎이 과도하게 구부러지는 것'],
    contraindications: ['손목 부상', '허리 문제'],
    modifications: [
      {
        condition: '유연성 부족',
        description: '무릎을 약간 구부리세요',
      },
    ],
    redFlags: ['허리 통증'],
  },
  {
    id: 'dyn_world_greatest',
    nameKo: '월드 그레이티스트 스트레치',
    nameEn: 'World Greatest Stretch',
    type: 'dynamic',
    category: 'sport_warmup',
    targetMuscles: ['iliopsoas', 'hamstrings', 'obliques'],
    secondaryMuscles: ['quadriceps', 'pectoralis_major'],
    equipment: ['mat'],
    difficulty: 'intermediate',
    defaultDuration: 6,
    durationUnit: 'reps',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '런지 자세에서 시작하세요',
      '앞발 안쪽에 같은 쪽 팔꿈치를 대세요',
      '그 팔을 천장으로 회전하세요',
      '양쪽 번갈아 6회 반복',
    ],
    breathingGuide: '회전할 때 들숨, 내릴 때 날숨',
    commonMistakes: ['뒷무릎이 바닥에 닿는 것'],
    contraindications: ['무릎 부상'],
    modifications: [],
    redFlags: ['무릎 통증'],
  },
  {
    id: 'dyn_lateral_lunge',
    nameKo: '사이드 런지',
    nameEn: 'Lateral Lunge',
    type: 'dynamic',
    category: 'sport_warmup',
    targetMuscles: ['adductors', 'gluteus_medius'],
    secondaryMuscles: ['quadriceps', 'hamstrings'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    defaultDuration: 10,
    durationUnit: 'reps',
    sets: 2,
    restBetweenSets: 15,
    instructions: [
      '다리를 넓게 벌리고 서세요',
      '한쪽으로 무게 중심을 옮기며 런지',
      '반대 다리는 곧게 펴세요',
      '양쪽 번갈아 10회 반복',
    ],
    breathingGuide: '내려갈 때 들숨, 올라올 때 날숨',
    commonMistakes: ['무릎이 안쪽으로 무너지는 것'],
    contraindications: ['무릎 부상'],
    modifications: [],
    redFlags: ['무릎 통증'],
  },
];

// ============================================
// PNF 스트레칭 (4개)
// ============================================

const PNF_STRETCHES: StretchExercise[] = [
  {
    id: 'pnf_hamstring',
    nameKo: 'PNF 햄스트링',
    nameEn: 'PNF Hamstring',
    type: 'pnf',
    category: 'posture_correction',
    targetMuscles: ['hamstrings'],
    secondaryMuscles: ['gastrocnemius'],
    equipment: ['mat', 'resistance_band'],
    difficulty: 'intermediate',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 3,
    restBetweenSets: 10,
    instructions: [
      '등을 대고 누워 한 다리를 들어올리세요',
      '밴드로 발을 잡고 스트레칭 위치로 당기세요',
      '6초간 밴드를 밀어내며 등장성 수축하세요',
      '이완 후 30초간 더 깊이 스트레칭하세요',
    ],
    breathingGuide: '수축 시 날숨, 이완 시 들숨',
    commonMistakes: ['수축 강도가 약한 것', '이완 시간이 부족한 것'],
    contraindications: ['급성 근육 부상'],
    modifications: [],
    redFlags: ['날카로운 통증'],
  },
  {
    id: 'pnf_hip_flexor',
    nameKo: 'PNF 장요근',
    nameEn: 'PNF Hip Flexor',
    type: 'pnf',
    category: 'posture_correction',
    targetMuscles: ['iliopsoas', 'rectus_femoris'],
    secondaryMuscles: ['tensor_fasciae_latae'],
    equipment: ['mat'],
    difficulty: 'intermediate',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 3,
    restBetweenSets: 10,
    instructions: [
      '반무릎 런지 자세에서 시작하세요',
      '골반을 후방경사로 틸트하세요',
      '6초간 뒷발로 바닥을 밀어 저항하세요',
      '이완 후 30초간 더 깊이 스트레칭하세요',
    ],
    breathingGuide: '수축 시 날숨, 이완 시 깊은 호흡',
    commonMistakes: ['허리가 과도하게 젖혀지는 것'],
    contraindications: ['무릎 부상'],
    modifications: [],
    redFlags: ['무릎 통증'],
  },
  {
    id: 'pnf_pec',
    nameKo: 'PNF 대흉근',
    nameEn: 'PNF Pec Stretch',
    type: 'pnf',
    category: 'posture_correction',
    targetMuscles: ['pectoralis_major', 'pectoralis_minor'],
    secondaryMuscles: ['deltoid'],
    equipment: ['wall'],
    difficulty: 'intermediate',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 3,
    restBetweenSets: 10,
    instructions: [
      '문틀 스트레칭 자세로 시작하세요',
      '6초간 벽을 밀어내며 저항하세요',
      '이완 후 한 발 더 앞으로 나가세요',
      '30초간 깊은 스트레칭을 유지하세요',
    ],
    breathingGuide: '수축 시 날숨, 이완 시 가슴 열기',
    commonMistakes: ['저항 강도가 너무 센 것'],
    contraindications: ['어깨 부상'],
    modifications: [],
    redFlags: ['어깨 날카로운 통증'],
  },
  {
    id: 'pnf_upper_trap',
    nameKo: 'PNF 상부 승모근',
    nameEn: 'PNF Upper Trapezius',
    type: 'pnf',
    category: 'posture_correction',
    targetMuscles: ['upper_trapezius'],
    secondaryMuscles: ['levator_scapulae'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 3,
    restBetweenSets: 10,
    instructions: [
      '목 옆으로 기울인 스트레칭 자세에서 시작',
      '손으로 머리를 잡고 6초간 머리로 손을 밀어내세요',
      '이완 후 조금 더 깊이 기울이세요',
      '30초간 유지하세요',
    ],
    breathingGuide: '수축 시 날숨, 이완 시 목 이완',
    commonMistakes: ['저항이 너무 강한 것'],
    contraindications: ['경추 문제'],
    modifications: [],
    redFlags: ['두통', '팔 저림'],
  },
];

// ============================================
// 회복 스트레칭 (6개)
// ============================================

const RECOVERY_STRETCHES: StretchExercise[] = [
  {
    id: 'str_corpse_pose',
    nameKo: '송장 자세',
    nameEn: 'Corpse Pose (Savasana)',
    type: 'static',
    category: 'recovery',
    targetMuscles: ['rectus_abdominis', 'erector_spinae'],
    secondaryMuscles: [],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 120,
    durationUnit: 'seconds',
    sets: 1,
    restBetweenSets: 0,
    instructions: [
      '등을 대고 편하게 누우세요',
      '팔은 몸 옆에 편하게 두세요',
      '눈을 감고 온몸의 긴장을 풀어주세요',
      '2분간 깊은 호흡을 하세요',
    ],
    breathingGuide: '복식호흡으로 완전히 이완',
    commonMistakes: ['생각이 계속 떠오르는 것'],
    contraindications: [],
    modifications: [
      {
        condition: '허리 불편',
        description: '무릎 아래에 베개',
      },
    ],
    redFlags: [],
  },
  {
    id: 'str_happy_baby',
    nameKo: '행복한 아기 자세',
    nameEn: 'Happy Baby Pose',
    type: 'static',
    category: 'recovery',
    targetMuscles: ['adductors', 'gluteus_maximus'],
    secondaryMuscles: ['hamstrings', 'erector_spinae'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 60,
    durationUnit: 'seconds',
    sets: 1,
    restBetweenSets: 0,
    instructions: [
      '등을 대고 누워 무릎을 구부리세요',
      '무릎을 가슴 쪽으로 당기세요',
      '양 손으로 발바닥 바깥쪽을 잡으세요',
      '부드럽게 좌우로 흔들어주세요',
    ],
    breathingGuide: '깊은 호흡으로 이완',
    commonMistakes: ['목이 긴장되는 것'],
    contraindications: ['무릎 부상', '임신'],
    modifications: [],
    redFlags: ['허리 통증'],
  },
  {
    id: 'str_supine_spinal_twist',
    nameKo: '누워서 척추 비틀기',
    nameEn: 'Supine Spinal Twist',
    type: 'static',
    category: 'recovery',
    targetMuscles: ['obliques', 'erector_spinae'],
    secondaryMuscles: ['gluteus_maximus', 'piriformis'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 45,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 10,
    instructions: [
      '등을 대고 누워 양 무릎을 세우세요',
      '양 무릎을 한쪽으로 천천히 내리세요',
      '반대쪽 어깨는 바닥에 붙여두세요',
      '45초 유지 후 반대쪽 반복',
    ],
    breathingGuide: '날숨에 더 깊이 비틀기',
    commonMistakes: ['어깨가 뜨는 것'],
    contraindications: ['디스크 탈출'],
    modifications: [],
    redFlags: ['허리 방사통'],
  },
  {
    id: 'str_knee_to_chest',
    nameKo: '무릎 당기기',
    nameEn: 'Knee to Chest',
    type: 'static',
    category: 'recovery',
    targetMuscles: ['gluteus_maximus', 'erector_spinae'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 10,
    instructions: [
      '등을 대고 누우세요',
      '한 무릎을 가슴 쪽으로 당기세요',
      '양 손으로 정강이를 잡으세요',
      '30초 유지 후 반대쪽 반복',
    ],
    breathingGuide: '깊게 호흡하며 허리 이완',
    commonMistakes: ['목이 긴장되는 것'],
    contraindications: [],
    modifications: [],
    redFlags: ['허리 통증 악화'],
  },
  {
    id: 'str_both_knees_chest',
    nameKo: '양 무릎 당기기',
    nameEn: 'Both Knees to Chest',
    type: 'static',
    category: 'recovery',
    targetMuscles: ['erector_spinae', 'gluteus_maximus'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['mat'],
    difficulty: 'beginner',
    defaultDuration: 30,
    durationUnit: 'seconds',
    sets: 2,
    restBetweenSets: 10,
    instructions: [
      '등을 대고 누우세요',
      '양 무릎을 가슴 쪽으로 당기세요',
      '양 손으로 정강이를 감싸세요',
      '부드럽게 좌우로 흔들어주세요',
    ],
    breathingGuide: '깊게 호흡하며 허리 이완',
    commonMistakes: ['목이 긴장되는 것'],
    contraindications: [],
    modifications: [],
    redFlags: ['허리 통증 악화'],
  },
  {
    id: 'str_legs_up_wall',
    nameKo: '벽에 다리 올리기',
    nameEn: 'Legs Up the Wall',
    type: 'static',
    category: 'recovery',
    targetMuscles: ['hamstrings', 'gastrocnemius'],
    secondaryMuscles: ['erector_spinae'],
    equipment: ['wall', 'mat'],
    difficulty: 'beginner',
    defaultDuration: 120,
    durationUnit: 'seconds',
    sets: 1,
    restBetweenSets: 0,
    instructions: [
      '엉덩이를 벽에 붙이고 누우세요',
      '다리를 벽 위로 올리세요',
      '팔은 옆으로 편하게 두세요',
      '2분간 이완하세요',
    ],
    breathingGuide: '깊은 복식호흡',
    commonMistakes: ['엉덩이가 벽에서 멀어지는 것'],
    contraindications: ['녹내장', '고혈압'],
    modifications: [
      {
        condition: '햄스트링 뻣뻣',
        description: '엉덩이를 벽에서 약간 떨어뜨리세요',
      },
    ],
    redFlags: ['어지러움'],
  },
];

// ============================================
// 전체 데이터베이스 내보내기
// ============================================

/**
 * 스트레칭 운동 전체 데이터베이스
 * 총 60개 운동 목록
 */
export const STRETCH_DATABASE: StretchExercise[] = [
  // 상체 (20개)
  ...CHEST_STRETCHES,         // 4개
  ...TRAPEZIUS_STRETCHES,     // 4개
  ...CERVICAL_STRETCHES,      // 4개
  ...SHOULDER_STRETCHES,      // 4개
  ...SPINE_STRETCHES,         // 4개

  // 하체 (20개)
  ...HIP_FLEXOR_STRETCHES,    // 4개
  ...HAMSTRING_STRETCHES,     // 4개
  ...GLUTE_STRETCHES,         // 4개
  ...QUADRICEPS_STRETCHES,    // 2개
  ...ADDUCTOR_STRETCHES,      // 3개
  ...CALF_STRETCHES,          // 3개

  // 동적 스트레칭 (10개)
  ...DYNAMIC_STRETCHES,

  // PNF 스트레칭 (4개)
  ...PNF_STRETCHES,

  // 회복 스트레칭 (6개)
  ...RECOVERY_STRETCHES,
];

/**
 * 카테고리별 스트레칭 조회
 */
export function getStretchesByCategory(category: StretchExercise['category']): StretchExercise[] {
  return STRETCH_DATABASE.filter(stretch => stretch.category === category);
}

/**
 * 타입별 스트레칭 조회
 */
export function getStretchesByType(type: StretchExercise['type']): StretchExercise[] {
  return STRETCH_DATABASE.filter(stretch => stretch.type === type);
}

/**
 * 난이도별 스트레칭 조회
 */
export function getStretchesByDifficulty(difficulty: StretchExercise['difficulty']): StretchExercise[] {
  return STRETCH_DATABASE.filter(stretch => stretch.difficulty === difficulty);
}

/**
 * ID로 스트레칭 조회
 */
export function getStretchById(id: string): StretchExercise | undefined {
  return STRETCH_DATABASE.find(stretch => stretch.id === id);
}
