/**
 * 음식 JSON 데이터에서 Supabase seed SQL 생성
 * Task 1.4: 기본 음식 DB 시딩 (500종)
 *
 * 사용법: npx tsx scripts/generate-food-seed.ts
 */

import * as fs from 'fs';
import * as path from 'path';

interface FoodData {
  id: string;
  name: string;
  nameEn: string;
  category: string;
  servingSize: string;
  servingGrams: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  sodium: number;
  trafficLight: string;
  isKorean: boolean;
  tags: string[];
}

// 카테고리 파일 목록과 한글명
const categories = [
  { file: 'rice.json', name: '밥류 (Rice)', count: 50 },
  { file: 'soup.json', name: '국/찌개 (Soup)', count: 50 },
  { file: 'side.json', name: '반찬 (Side Dishes)', count: 80 },
  { file: 'meat.json', name: '고기 (Meat)', count: 50 },
  { file: 'seafood.json', name: '해산물 (Seafood)', count: 40 },
  { file: 'noodle.json', name: '면류 (Noodle)', count: 40 },
  { file: 'bread.json', name: '빵/디저트 (Bread/Dessert)', count: 50 },
  { file: 'beverage.json', name: '음료 (Beverage)', count: 40 },
  { file: 'fruit.json', name: '과일 (Fruit)', count: 50 },
  { file: 'fastfood.json', name: '패스트푸드 (Fast Food)', count: 50 },
];

// SQL 문자열 이스케이프
function escapeSQL(str: string): string {
  return str.replace(/'/g, "''");
}

// 단일 음식 INSERT VALUE 생성
function foodToSQLValue(food: FoodData): string {
  const tags = food.tags.map((t) => `'${escapeSQL(t)}'`).join(', ');
  return `  ('${escapeSQL(food.name)}', '${escapeSQL(food.nameEn)}', '${food.category}', '${escapeSQL(food.servingSize)}', ${food.servingGrams}, ${food.calories}, ${food.protein}, ${food.carbs}, ${food.fat}, ${food.fiber}, ${food.sugar}, ${food.sodium}, '${food.trafficLight}', ${food.isKorean}, ARRAY[${tags}])`;
}

// 카테고리별 INSERT 문 생성
function generateCategorySQL(
  categoryName: string,
  expectedCount: number,
  foods: FoodData[]
): string {
  const lines: string[] = [];
  lines.push(`-- =====================================================`);
  lines.push(`-- ${categoryName} - ${foods.length}종`);
  lines.push(`-- =====================================================`);
  lines.push(
    `INSERT INTO foods (name, name_en, category, serving_size, serving_grams, calories, protein, carbs, fat, fiber, sugar, sodium, traffic_light, is_korean, tags)`
  );
  lines.push(`VALUES`);

  const values = foods.map((food, i) => {
    const value = foodToSQLValue(food);
    return i < foods.length - 1 ? value + ',' : value + ';';
  });

  lines.push(...values);
  lines.push('');

  return lines.join('\n');
}

// 메인 실행
async function main() {
  const dataDir = path.join(process.cwd(), 'data', 'foods');
  const outputPath = path.join(process.cwd(), 'supabase', 'seed-foods.sql');

  // SQL 헤더
  const header = `-- Seed Script: foods 테이블 시딩
-- Task 1.4: 기본 음식 DB 시딩 (500종)
-- Date: 2025-12-01
-- Auto-generated by scripts/generate-food-seed.ts
--
-- 사용법:
-- 1. Supabase Dashboard > SQL Editor 에서 실행
-- 2. 또는 npx supabase db reset (로컬 개발 시)
--
-- 참고: 이 파일은 data/foods/*.json 파일의 데이터를 기반으로 생성됨

-- 기존 데이터 삭제 (필요시)
-- TRUNCATE TABLE foods RESTART IDENTITY;

`;

  let totalCount = 0;
  const sqlParts: string[] = [header];

  // 각 카테고리 처리
  for (const category of categories) {
    const filePath = path.join(dataDir, category.file);

    if (!fs.existsSync(filePath)) {
      console.error(`파일을 찾을 수 없음: ${filePath}`);
      continue;
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    const foods: FoodData[] = JSON.parse(content);

    console.log(`${category.name}: ${foods.length}개 (예상: ${category.count})`);
    totalCount += foods.length;

    const sql = generateCategorySQL(category.name, category.count, foods);
    sqlParts.push(sql);
  }

  // 푸터
  const footer = `-- =====================================================
-- 총 ${totalCount}종 음식 데이터 시딩 완료
-- =====================================================
`;
  sqlParts.push(footer);

  // 파일 쓰기
  fs.writeFileSync(outputPath, sqlParts.join('\n'), 'utf-8');
  console.log(`\n✅ SQL 파일 생성 완료: ${outputPath}`);
  console.log(`📊 총 음식 수: ${totalCount}종`);
}

main().catch(console.error);
