'use client';

/**
 * 이용약관 페이지 (한/영 지원)
 * SDD-LEGAL-SUPPORT.md §3.1
 */

import { useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { ArrowLeft, FileText } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type Lang = 'ko' | 'en';

const TERMS_KO = [
  {
    id: 'purpose',
    title: '제1조 (목적)',
    content: `이 약관은 이룸(Yiroom, 이하 "서비스")을 제공하는 운영자(이하 "회사")와 서비스를 이용하는 회원(이하 "이용자") 간의 권리, 의무 및 책임사항을 규정함을 목적으로 합니다.`,
  },
  {
    id: 'definitions',
    title: '제2조 (정의)',
    content: `① "서비스"란 이룸 앱을 통해 제공되는 AI 피부 분석, 체형 분석, 퍼스널컬러 진단, 운동 및 영양 관리 등 모든 서비스를 의미합니다.
② "이용자"란 이 약관에 동의하고 서비스를 이용하는 회원을 말합니다.
③ "콘텐츠"란 서비스 내에서 이용자가 생성하거나 업로드한 텍스트, 이미지, 분석 결과 등을 의미합니다.
④ "AI 분석"이란 이용자가 업로드한 이미지를 Google Gemini 등의 AI 모델을 통해 분석하여 제공하는 결과를 말합니다.`,
  },
  {
    id: 'agreement',
    title: '제3조 (약관의 효력 및 변경)',
    content: `① 이 약관은 서비스 화면에 게시하거나 기타의 방법으로 이용자에게 공지함으로써 효력이 발생합니다.
② 회사는 필요한 경우 관련 법령을 위반하지 않는 범위에서 이 약관을 변경할 수 있습니다.
③ 약관이 변경되는 경우 회사는 변경 내용을 시행일 7일 전부터 서비스 내 공지합니다.`,
  },
  {
    id: 'registration',
    title: '제4조 (서비스 이용 계약)',
    content: `① 이용계약은 이용자가 약관의 내용에 동의하고, 회사가 정한 가입 절차를 완료함으로써 체결됩니다.
② 회사는 다음 각 호에 해당하는 경우 이용 신청을 거부할 수 있습니다:
  1. 실명이 아니거나 타인의 정보를 이용한 경우
  2. 이전에 이용 자격을 상실한 적이 있는 경우
  3. 기타 서비스 운영에 지장을 초래하는 경우`,
  },
  {
    id: 'service',
    title: '제5조 (서비스의 제공)',
    content: `① 회사는 다음과 같은 서비스를 제공합니다:
  1. AI 기반 피부, 체형, 퍼스널컬러 분석
  2. 맞춤형 운동 및 영양 관리 추천
  3. AI 웰니스 코치 서비스
  4. 제품 추천 및 정보 제공
  5. 소셜 기능 (피드, 챌린지, 리더보드)
② 서비스는 연중무휴, 1일 24시간 제공함을 원칙으로 합니다.
③ 회사는 시스템 점검, 장애 등의 사유로 서비스 제공을 일시적으로 중단할 수 있습니다.`,
  },
  {
    id: 'obligation-company',
    title: '제6조 (회사의 의무)',
    content: `① 회사는 관련 법령과 이 약관이 정하는 바에 따라 지속적이고 안정적인 서비스를 제공합니다.
② 회사는 이용자의 개인정보를 보호하기 위해 보안 시스템을 갖추고 개인정보처리방침을 공시합니다.
③ 회사는 서비스 이용과 관련하여 이용자로부터 제기된 의견이나 불만이 정당하다고 인정되면 적절한 조치를 취합니다.`,
  },
  {
    id: 'obligation-user',
    title: '제7조 (이용자의 의무)',
    content: `① 이용자는 다음 행위를 하여서는 안 됩니다:
  1. 타인의 정보 도용
  2. 서비스를 이용하여 얻은 정보의 무단 복제, 배포
  3. 회사의 저작권, 지적재산권 침해
  4. 회사 및 제3자의 명예를 훼손하는 행위
  5. 기타 관련 법령이나 약관에 위반되는 행위
② 이용자는 분석을 위해 업로드하는 이미지가 본인의 것임을 확인합니다.`,
  },
  {
    id: 'termination',
    title: '제8조 (계정 관리 및 해지)',
    content: `① 회사는 이용자가 약관을 위반하거나 서비스 운영을 방해한 경우 서비스 이용을 제한할 수 있습니다.
② 이용자는 언제든지 서비스 내 설정에서 회원 탈퇴를 요청할 수 있습니다.
③ 탈퇴 시 모든 개인정보와 분석 결과는 30일 이내에 완전 파기됩니다.
④ 탈퇴 후 동일 이메일로 재가입은 가능하나, 이전 데이터는 복구할 수 없습니다.`,
  },
  {
    id: 'ip',
    title: '제9조 (지적재산권)',
    content: `① 서비스에 포함된 콘텐츠에 대한 저작권 및 지적재산권은 회사에 귀속됩니다.
② 이용자가 업로드한 이미지에 대한 저작권은 이용자에게 있으며, 회사는 서비스 제공 목적으로만 이를 이용합니다.
③ AI 분석 결과에 대한 저작권은 회사에 귀속되며, 이용자는 개인적 용도로 자유롭게 이용할 수 있습니다.`,
  },
  {
    id: 'disclaimer',
    title: '제10조 (면책조항)',
    content: `① 회사는 천재지변, 전쟁, 기간통신사업자의 서비스 중지 등 불가항력으로 인한 서비스 제공 불가에 대해 책임을 지지 않습니다.
② AI 분석 결과는 참고용이며, 의료적 진단이나 치료를 대체하지 않습니다.
③ 이용자가 서비스 내 제휴 링크를 통해 외부 서비스를 이용하는 경우, 해당 외부 서비스에서 발생하는 문제에 대해 회사는 책임지지 않습니다.`,
  },
  {
    id: 'dispute',
    title: '제11조 (분쟁 해결)',
    content: `① 이 약관에 명시되지 않은 사항은 관련 법령에 따릅니다.
② 서비스 이용으로 발생한 분쟁에 대해 소송이 제기될 경우 회사의 본사 소재지를 관할하는 법원을 관할 법원으로 합니다.`,
  },
];

const TERMS_EN = [
  {
    id: 'purpose',
    title: '1. Purpose',
    content: `These Terms of Service ("Terms") govern your use of the Yiroom platform and services ("Service") provided by Yiroom ("Company"). By accessing or using the Service, you agree to be bound by these Terms.`,
  },
  {
    id: 'definitions',
    title: '2. Definitions',
    content: `"Service" refers to all services provided through the Yiroom platform, including AI-powered skin analysis, body type analysis, personal color diagnosis, workout and nutrition management, and AI coaching.
"User" refers to any individual who agrees to these Terms and uses the Service.
"Content" refers to text, images, analysis results, and other materials created or uploaded by Users within the Service.
"AI Analysis" refers to results generated by processing user-uploaded images through AI models including Google Gemini.`,
  },
  {
    id: 'agreement',
    title: '3. Effectiveness and Changes',
    content: `These Terms become effective when posted on the Service screen or communicated to Users by other means.
The Company may modify these Terms as necessary within the scope of applicable laws.
Users will be notified of changes at least 7 days in advance through in-service announcements.`,
  },
  {
    id: 'registration',
    title: '4. Service Agreement',
    content: `The service agreement is established when the User agrees to these Terms and completes the registration process.
The Company may refuse registration in the following cases:
  1. Using a false identity or another person's information
  2. Previously having lost eligibility to use the Service
  3. Other cases that may impede Service operations`,
  },
  {
    id: 'service',
    title: '5. Service Description',
    content: `The Company provides the following services:
  1. AI-powered skin, body type, and personal color analysis
  2. Personalized workout and nutrition management
  3. AI wellness coaching
  4. Product recommendations and information
  5. Social features (feeds, challenges, leaderboards)
The Service is available 24/7 in principle, but may be temporarily suspended for maintenance or technical reasons.`,
  },
  {
    id: 'obligation-company',
    title: '6. Company Obligations',
    content: `The Company shall provide continuous and stable Service in accordance with applicable laws and these Terms.
The Company shall maintain security systems to protect User personal information and publish a Privacy Policy.
The Company shall take appropriate measures when User complaints or feedback are deemed valid.`,
  },
  {
    id: 'obligation-user',
    title: '7. User Obligations',
    content: `Users must not:
  1. Use another person's identity or information
  2. Reproduce or distribute information obtained through the Service without authorization
  3. Infringe on the Company's copyrights or intellectual property
  4. Defame or harm the Company or third parties
  5. Violate applicable laws or these Terms
Users confirm that images uploaded for analysis are their own.`,
  },
  {
    id: 'termination',
    title: '8. Account Management',
    content: `The Company may restrict Service use if a User violates these Terms or disrupts Service operations.
Users may request account deletion at any time through the Settings menu.
Upon deletion, all personal data and analysis results will be permanently destroyed within 30 days.
Re-registration with the same email is possible, but previous data cannot be recovered.`,
  },
  {
    id: 'ip',
    title: '9. Intellectual Property',
    content: `All content within the Service is owned by the Company.
Users retain copyright over images they upload. The Company uses uploaded images solely for providing the Service.
AI analysis results are owned by the Company. Users may freely use their analysis results for personal purposes.`,
  },
  {
    id: 'disclaimer',
    title: '10. Disclaimers',
    content: `The Company is not liable for service interruptions caused by force majeure events (natural disasters, war, infrastructure failures, etc.).
AI analysis results are for reference purposes only and do not constitute medical diagnosis or treatment. Always consult qualified professionals for health decisions.
When Users access external services through affiliate links within the Service, the Company is not responsible for issues arising from those external services.`,
  },
  {
    id: 'dispute',
    title: '11. Governing Law',
    content: `Matters not specified in these Terms shall be governed by applicable laws.
Any disputes arising from Service use shall be subject to the exclusive jurisdiction of the courts at the location of the Company's headquarters in the Republic of Korea.`,
  },
];

export default function TermsPage() {
  const searchParams = useSearchParams();
  const initialLang = searchParams.get('lang') === 'en' ? 'en' : 'ko';
  const [lang, setLang] = useState<Lang>(initialLang);
  const sections = lang === 'ko' ? TERMS_KO : TERMS_EN;

  return (
    <div className="min-h-screen bg-background" data-testid="terms-page">
      {/* 헤더 */}
      <div className="sticky top-0 z-10 bg-background/95 backdrop-blur border-b px-4 py-3">
        <div className="max-w-2xl mx-auto flex items-center gap-3">
          <Link
            href="/help"
            className="p-2 -ml-2 hover:bg-muted rounded-lg transition-colors"
            aria-label={lang === 'ko' ? '고객센터로 돌아가기' : 'Back to Help Center'}
          >
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <div className="flex-1">
            <h1 className="font-bold text-foreground flex items-center gap-2">
              <FileText className="w-5 h-5" />
              {lang === 'ko' ? '이용약관' : 'Terms of Service'}
            </h1>
          </div>
          <div className="flex gap-1.5">
            <button
              onClick={() => setLang('ko')}
              className={`px-2.5 py-1 text-xs rounded-md transition-colors ${
                lang === 'ko'
                  ? 'bg-primary text-primary-foreground'
                  : 'bg-muted text-muted-foreground hover:bg-muted/80'
              }`}
              aria-label="한국어로 보기"
            >
              한국어
            </button>
            <button
              onClick={() => setLang('en')}
              className={`px-2.5 py-1 text-xs rounded-md transition-colors ${
                lang === 'en'
                  ? 'bg-primary text-primary-foreground'
                  : 'bg-muted text-muted-foreground hover:bg-muted/80'
              }`}
              aria-label="View in English"
            >
              EN
            </button>
          </div>
        </div>
      </div>

      {/* 콘텐츠 */}
      <div className="max-w-2xl mx-auto px-4 py-6 space-y-4">
        <p className="text-sm text-muted-foreground">
          {lang === 'ko'
            ? '최종 수정일: 2026년 2월 20일 | 시행일: 2026년 2월 20일'
            : 'Last updated: February 20, 2026 | Effective: February 20, 2026'}
        </p>

        {sections.map((section) => (
          <Card key={section.id}>
            <CardHeader className="pb-2">
              <CardTitle className="text-base">{section.title}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground whitespace-pre-line">{section.content}</p>
            </CardContent>
          </Card>
        ))}

        {/* 부칙 / Supplementary */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base">
              {lang === 'ko' ? '부칙' : 'Supplementary Provisions'}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              {lang === 'ko'
                ? '이 약관은 2026년 2월 20일부터 시행합니다.'
                : 'These Terms are effective as of February 20, 2026.'}
            </p>
          </CardContent>
        </Card>

        {/* 문의 */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base">{lang === 'ko' ? '문의' : 'Contact'}</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              {lang === 'ko' ? '이메일' : 'Email'}: contact@yiroom.app
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
